name: go

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        go: [ 
          '1.18', 
          '1.19',
          '1.20', 
          '1.21'
        ]

    name: Go ${{ matrix.go }}
    steps:
      - uses: actions/checkout@v4

      - name: Setup go
        uses: actions/setup-go@v4
        with:
          go-version: ${{ matrix.go }}
      
      - name: Install
        run: go get
      
      - name: Test
        run: go test -v -cover ./...
