name: go

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        go: [ 
          # '1.2', 
          # '1.3', 
          # '1.4', 
          '1.16' 
        ]

    name: Go ${{ matrix.go }} sample
    steps:
      - uses: actions/checkout@v2
        path: src/emartech/escher-go

      - name: Setup go
        uses: actions/setup-go@v2
        with:
          go-version: ${{ matrix.go }}
      
      - name: Install & Test
        run: |
          
          go test -v -cover ./... 
        env:
          GOPATH: /home/runner/work/src/emartech/escher-go
